[build-system]
requires = [
    "setuptools>=65.5.0",
    "wheel>=0.41.0"
]
build-backend = "setuptools.build_meta"

[project]
name = "rag-proto"
version = "0.1.0"
description = "RAG Prototype with MultiLingual Support"
requires-python = ">=3.8"

[tool.setuptools]
packages = []
